[tool.poetry]
name = "projekat-retail-sales"
version = "1.0.0"
description = "Predviđanje zarade od prodaje mješovite robe (cijena × količina − popust)"
authors = ["Jovan Popović <jovan.popovic3@udg.edu.me>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26"
pandas = "^2.2"
matplotlib = "^3.8"
seaborn = "^0.13"
scikit-learn = "^1.4"
jupyter = "^1.0"
ipykernel = "^6.29"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
